### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by axelson** [threeaccents/json_to_elixir#14]
Hi @threeaccents! 👋 

Thanks for this project! It's already been helpful for me in some side projects 😄

I have a question. Were you intending for this project to be open source? I couldn't find a license anywhere in the repo.

I have some ideas seem interesting to me to add to this such as https://github.com/solnic/drops integration, and also showing a raw elixir map/term.

**Comment by threeaccents** [comment]
Hey @axelson yes this is 100% open source. I will be adding the license right now thank you for pointing it out! 

I've been wanting to add the same things just never got around to it. So a contribution would be much appreciated!

**Comment by axelson** [comment]
Great, I'm glad to hear it!
